project_id = "pnqcbnmrfzqihymmzhkb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 10000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[edge_runtime]
enabled = true
port = 54329

[functions.qbo-oauth-initiate]
verify_jwt = false

[functions.qbo-oauth-callback]
verify_jwt = false

[functions.qbo-disconnect]
verify_jwt = true

[functions.generate-template-test-data]
verify_jwt = true

[functions.batch-processor]
verify_jwt = false

[functions.clear-pending-orders]
verify_jwt = true

[functions.generate-test-orders]
verify_jwt = true

[functions.import-csv-data]
verify_jwt = true